### ISSUE TITLE
Adafruit_NeoPixel not defined

### ISSUE THREAD

**Issue by DomThePro02** [CalebKussmaul/Stranger-Things-Integrated#1]
When i run app.py it is giving me this error:

Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import stranger
  File "/home/pi/Stranger-Things-Integrated/stranger.py", line 23, in <module>
    strip = Adafruit_NeoPixel(LED_COUNT, GPIO_PIN, LED_FREQ_HZ, LED_DMA, LED_INVERT, LED_BRIGHTNESS)
NameError: name 'Adafruit_NeoPixel' is not defined

I'm teaching myself how to use python through RasPi in a 3b+ and ive been solving problems but i cant get past this

**Comment by CalebKussmaul** [comment]
Hey @DomThePro02, it seems that I included instructions in [requirements.txt ](https://github.com/CalebKussmaul/Stranger-Things-Integrated/blob/master/requirements.txt) that should have been in the Readme:

> First install rpi_ws281x from https://github.com/jgarff/rpi_ws281x

That should fix the issue.

**Comment by DomThePro02** [comment]
I had already installed the rpi_ws281x, with the included python wrapper, and I fixed and enabled spi and i2c beforehand. I have all of the adafruit libraries with circuitpython installed as well.

**Comment by DomThePro02** [comment]
@CalebKussmaul I originally figured that I didn't have the correct libraries, and im new to Python and Raspberry Pi, seems like an odd issue. Im running python 3 though.

**Comment by CalebKussmaul** [comment]
@DomThePro02 ah that would do it. This project uses Python 2 and isn't compatible with Python 3.

**Comment by DomThePro02** [comment]
I'll switch over the defaults and see what happens!

**Comment by ClarDold** [comment]
Feb 2025.
I still get the error message.
Raspberry Pi4, Debian GNU/Linux 12 (bookworm)

I used venv for the pip install -r requirements.txt. I can see .venv/lib/python3.11/site-packages/rpi_ws281x/rpi_ws281x.py

Do I have to overwrite the rpi_ws281x with one from https://github.com/jgarff/rpi_ws281x ?
The Readme says * Python - https://github.com/rpi-ws281x/rpi-ws281x-python
which in turn says "Most users should simply run: sudo pip install rpi_ws281x"
I didn't do a sudo, because I am in the venv, and have broken the base Python in the past.

(.venv) clarence@Pi4:~/stranger/CalebKussmaul/Stranger-Things-Integrated $ python app.py
Traceback (most recent call last):
  File "/home/clarence/stranger/CalebKussmaul/Stranger-Things-Integrated/app.py", line 2, in <module>
    import stranger
  File "/home/clarence/stranger/CalebKussmaul/Stranger-Things-Integrated/stranger.py", line 22, in <module>
    strip = Adafruit_NeoPixel(LED_COUNT, GPIO_PIN, LED_FREQ_HZ, LED_DMA, LED_INVERT, LED_BRIGHTNESS)
            ^^^^^^^^^^^^^^^^^
NameError: name 'Adafruit_NeoPixel' is not defined
